### ISSUE TITLE
Missalignment of selected rectange around node

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#12]
I noticed that the selected rectangle around a node is not aligned correctly, see the image which shows a gap on the lower side but no gap on the upper side. 

![image](https://user-images.githubusercontent.com/1054990/92978788-ab2d1280-f445-11ea-9d28-01c03b09eeaf.png)

At higher zoom settings, the misalignment goes away, see the next image. 

![image](https://user-images.githubusercontent.com/1054990/92978879-e92a3680-f445-11ea-989c-a8eb544d559a.png)

**Comment by evilnose** [comment]
This seems to be due to float values being rounded to integer before drawing, since if I set the border and padding to even values, this effect seems to vanish.

Since GraphicsContext supports antialiasing though, this really shouldn't be happening. I think now this is due to me using `wx.Pen` or `wx.Brush` (which use integers instead of floats) instead of the `GraphicsContext` equivalent. I will replace those functions everywhere.

**Comment by evilnose** [comment]
Finally figured out the reason ('twas not what I guessed before). I'm documenting the issue here in case others encounter this in the future.

See https://www.cairographics.org/FAQ/#sharp_lines. Basically, when lines are drawn, they are not drawn centered on the pixel "squares", but rather on the lines between the pixel "squares". This creates a problem when drawing thin (1-pixel) lines. In our case, to maintain the sharpness of the lines (despite antialiasing), the graphics backend drew in a misaligned way (i.e. on the pixel squares, with pixel width 1).

To fix this problem, I took the recommended approach of 1) aligning the rectangle position and size to integer coordinates, and 2) rounding the border width to the nearest even integer, so that the lines stay sharp and aligned. This may result in the tiniest bit of inaccuracy when drawn (especially in smaller zoom scales), but to have the right alignment, we'd have to deal with it.
