### ISSUE TITLE
Autolayout doesn't work for complex reactions

### ISSUE THREAD

**Issue by hsauro** [evilnose/PyRKViewer#76]
The autolayout plugin doesn't work for complex reactions. In particular, the arc centers aren't positioned correctly

**Comment by SunnyXu** [comment]
fixed. making the reactions look like straight lines with assigned handle positions. the arc center control also get fixed by assign the handle positions after adjusting the center positions. Details see commit (https://github.com/evilnose/PyRKViewer/commit/72d11d2642a0e7dbbc3943eef176890c9455a066).
